### ISSUE TITLE
[v0.20.0] Docker deployment regression - @node-rs/argon2 and Prisma CLI issues

### ISSUE THREAD

**Issue by bkidy** [wasp-lang/wasp#3578]
## Bug Description

After upgrading from Wasp 0.18 to 0.20, Docker deployment fails with native module and CLI path issues on Alpine Linux.

## Reproduction Steps

1. **Setup**: GitHub Actions workflow using `ubuntu-latest` (glibc)
2. **Build**: Run `wasp build` (generates `.wasp/build` directory)
3. **Docker**: Build using generated Dockerfile (Alpine 3.20 base image)
4. **Result**: Build fails with errors

### Error 1: argon2 native module
```
Error: Failed to load native binding
Cannot find module './argon2.linux-x64-musl.node'
Cannot find module '@node-rs/argon2-linux-x64-musl'
```

### Error 2: Prisma CLI not found
```
> npm run db-migrate-prod
sh: prisma: not found
```

## Environment

- **Wasp 0.18**: ✅ Works perfectly (no custom Dockerfile needed)
- **Wasp 0.20**: ❌ Fails (requires custom Dockerfile workaround)
- **CI**: GitHub Actions (`ubuntu-latest`, glibc)
- **Docker Base**: `node:22.12.0-alpine3.20` (musl libc)
- **Deployment**: GitHub Actions → Docker build → GitHub Container Registry

### Issue 1: Cross-platform native module (@node-rs/argon2)

The generated Dockerfile copies the entire `.wasp/out/sdk` directory from GitHub Actions build:

```dockerfile
COPY sdk .wasp/out/sdk
```

This SDK includes `node_modules` with **glibc** version of `@node-rs/argon2` (installed on GitHub Actions runner). When the Docker container runs on Alpine (musl), it cannot load the glibc native binaries.

**Why this worked in Wasp 0.18**: Unknown, possibly different Dockerfile generation logic or different dependency handling.

### Issue 2: Prisma CLI PATH

The generated Dockerfile structure:
```dockerfile
WORKDIR /app
COPY --from=server-builder /app/node_modules ./node_modules  # Prisma is here
WORKDIR /app/.wasp/build/server
ENTRYPOINT ["npm", "run", "start-production"]  # Calls 'prisma migrate deploy'
```

The `db-migrate-prod` script calls `prisma` directly, but the binary is in `/app/node_modules/.bin/prisma`, not in PATH from the current WORKDIR.

## Workaround

Create `app/Dockerfile` with the following content (Wasp automatically appends this to the generated Dockerfile):

```dockerfile
# Fix @node-rs/argon2 for Alpine Linux (musl libc)
# When npm install runs on macOS/Linux (glibc), it only downloads glibc binaries.
# Alpine Linux needs linux-x64-musl binaries which must be installed explicitly.
RUN npm install @node-rs/argon2-linux-x64-musl@1.8.3 --prefix /app --save=false --ignore-scripts

# Fix Prisma CLI path
# Prisma is in /app/node_modules, add it to PATH so db-migrate-prod can find it
ENV PATH="/app/node_modules/.bin:${PATH}"
```

## Expected Behavior

Wasp 0.20 should work like 0.18 - **no custom Dockerfile should be needed** for standard Docker deployment scenarios.

## Impact

This is a **regression bug** that breaks existing deployment workflows when upgrading from 0.18 to 0.20.

## Additional Context

- Wasp 0.20.1 (released 2025-12-31) does not fix this issue
- No similar issues found in GitHub Issues for v0.20.x
- This affects any deployment using:
  - Cross-platform builds (e.g., macOS/Linux CI → Alpine Docker)
  - GitHub Actions → Docker workflow

**Comment by cprecioso** [comment]
Hi @bkidy, we had this same issue reported previously [on Discord](https://discord.com/channels/686873244791210014/1273962730566717471), and the user solved it by running `wasp clean`, removing their `package-lock.json`, and regenerating everything.
Can you check if that fixes your issue?

**Comment by cprecioso** [comment]
Hi @bkidy I will close this issue now for inactivity. That's not the end of it though! We can reopen if you come back to us with more information. Otherwise, I hope your issue has been solved. 😊
